name: "Autonomous PR Review"
description: "Fetch PR diff, ask Claude via API, and post a summary comment."

inputs:
  mcp_token:
    required: true
    description: "GitHub MCP token"
  anthropic_api_key:
    required: true
    description: "Anthropic API key"
  github_token:
    required: true
    description: "GitHub token (PAT recommended) for posting comments"
  repo:
    required: true
    description: "owner/repo"
  pr_number:
    required: true
    description: "PR number (same as issue number)"
  reply_style:
    required: false
    default: "요약 / 중요한 이슈 / 개선 제안 / 테스트 제안"
    description: "Format guidance for the review comment"
  model:
    required: false
    # ⚠️ 여기 값은 '너 계정에서 실제로 사용 가능한 모델 ID'로 바꿔야 함
    # 일단 안전하게 input으로 받게 해두고, 미지정 시 오류 안내 코멘트로 빠지게 처리
    default: "claude-sonnet-4-20250514"
    description: "Claude model id (must be available for your API key)"
  max_diff_chars:
    required: false
    default: "30000"
    description: "Max diff chars to send to model"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install deps for this action
      shell: bash
      run: |
        cd "$GITHUB_ACTION_PATH"
        npm ci

    - name: Run review agent (Direct API)
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        BOT_TOKEN: ${{ inputs.github_token }}
        REPO: ${{ inputs.repo }}
        PR_NUMBER: ${{ inputs.pr_number }}
        REPLY_STYLE: ${{ inputs.reply_style }}
        MODEL: ${{ inputs.model }}
        MAX_DIFF_CHARS: ${{ inputs.max_diff_chars }}
        MCP_TOKEN: ${{ inputs.mcp_token }}
      run: |
        node "$GITHUB_ACTION_PATH/scripts/review-agent.mjs"
